name: CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
    workflow_dispatch:

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
        steps:
        - uses: actions/checkout@v3
          with:
              fetch-depth: 0
              submodules: recursive
                
        - name: Setup .NET
          uses: actions/setup-dotnet@v3
          with:
              dotnet-version: 8.0.x
                
        - name: Restore dependencies
          run: dotnet restore
        
        - name: Restore Tools
          run: dotnet tool restore
          working-directory: examples/ShyFox.MonoPack.Tool.Example
            
        - name: Build
          run: dotnet build --no-restore -c Release
            
        - name: Test
          run: dotnet test --no-build -c Release

        # - name: Package
        #   if: github.event_name != 'pull_request' && matrix.os == 'ubuntu-latest'
        #   run: dotnet pack --no-build --output ./artifacts
            
        # - name: Upload artifacts
        #   if: github.event_name != 'pull_request' && matrix.os == 'ubuntu-latest'
        #   uses: actions/upload-artifact@v3
        #   with:
        #       name: nuget-packages
        #       path: ./artifacts/*.nupkg